{% set name = "freeglut" %}
{% set version = "3.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/freeglut/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3c0bcb915d9b180a97edaebd011b7a1de54583a838644dcd42bb0ea0c6f3eaec
  patches:                            # [win]
    - disable_autolink_windows.patch  # [win]

build:
  number: 1
  skip: true  # [osx]
  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=freeglut
    # very good backwards compatibility
    - {{ pin_subpackage("freeglut", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base
    - pkg-config
    - m2-patch  # [win]

  host:
    # The relevant packages to build freeglut https://github.com/freeglut/freeglut/blob/63c0e78d84ecbfcf8accd8bac04404427899053b/README.cmake#L42
    - libglu 9.0.3                       # [linux]
    - libxcb 1.17                        # [linux]
    - xorg-libx11                        # [linux]
    - libgl-devel                        # [linux]
    - xorg-libxi                         # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-libxrandr                     # [linux]

test:
  files:
    - test
  requires:
    - {{ compiler('c') }}
    - cmake
    - ninja-base
    - pkg-config                         # [linux]
    # Dependencies needed for testing
    - libglu                             # [linux and not s390x]
    - libxcb                             # [linux]
    - xorg-libx11                        # [linux]
    - libgl-devel                        # [linux]
    - xorg-libxi                         # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-libxrandr                     # [linux]
  # test commands are moved to run_test.sh and run_test.bat

about:
  home: https://freeglut.sourceforge.net/
  dev_url: https://github.com/freeglut/freeglut
  doc_url: https://freeglut.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A GUI based on OpenGL.
  description: |
    Open-source alternative to the OpenGL Utility Toolkit (GLUT) library.

extra:
  recipe-maintainers:
    - jakirkham
    - shadowwalkersb
    - wolfv