{% set version = "3.4.0" %}

package:
  name: freeglut
  version: {{ version }}

source:
  url: http://sourceforge.net/projects/freeglut/files/freeglut/{{ version }}/freeglut-{{ version }}.tar.gz
  sha256: 3c0bcb915d9b180a97edaebd011b7a1de54583a838644dcd42bb0ea0c6f3eaec
  patches:
    - disable_autolink_windows.patch
    - 96.patch

build:
  number: 0
  # mesa-libgl-devel isn't available on s390x
  skip: true  # [osx or (linux and s390x)]
  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=freeglut
    # very good backwards compatibility
    - {{ pin_subpackage("freeglut", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base
    - pkg-config
    - m2-patch                          # [win]
    - patch                             # [not win]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libxfixes-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux and not s390x]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
  host:
    - libglu 9.0.0                      # [linux and not s390x]
    - libxcb                             # [linux]
  run:
    - libxcb                             # [linux]

test:
  files:
    - test
  requires:
    - {{ compiler('c') }}
    - cmake
    - ninja-base
    - pkg-config
    - libglu                            # [linux and not s390x]
    - libxcb                             # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libxfixes-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux and not s390x]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libselinux') }}  # [linux]
  commands:
    # Test includes.
    - test -d "${PREFIX}/include/GL"  # [linux]

      # Test libraries.
    - test ! -f "${PREFIX}/lib/libglut.a"   # [linux]
    - test -f "${PREFIX}/lib/libglut.so"    # [linux]
    - ldd "${PREFIX}/lib/libglut.so"        # [linux]

    # Test Windows includes and libraries.
    - if not exist %LIBRARY_INC%\\GL\\freeglut.h     exit 1   # [win]
    - if not exist %LIBRARY_INC%\\GL\\freeglut_ext.h exit 1   # [win]
    - if not exist %LIBRARY_INC%\\GL\\freeglut_std.h exit 1   # [win]
    - if not exist %LIBRARY_INC%\\GL\\glut.h         exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\freeglut.lib       exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\freeglut.dll       exit 1   # [win]

about:
  home: http://freeglut.sourceforge.net/
  dev_url: https://github.com/freeglut/freeglut
  doc_url: https://freeglut.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A GUI based on OpenGL.

extra:
  recipe-maintainers:
    - jakirkham
    - shadowwalkersb
    - wolfv