{% set name = "freeglut" %}
{% set version = "3.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/freeglut/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3c0bcb915d9b180a97edaebd011b7a1de54583a838644dcd42bb0ea0c6f3eaec

build:
  number: 0
  # mesa-libgl-devel isn't available on s390x
  skip: true  # [osx or (linux and s390x)]
  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=freeglut
    # very good backwards compatibility
    - {{ pin_subpackage("freeglut", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base
    - pkg-config
    - m2-patch                          # [win]
    - patch                             # [not win]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libxfixes-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux and not s390x]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
  host:
    - libglu 9.0.0                      # [linux and not s390x]
    - libxcb 1.15                        # [linux]
  run:
    - libxcb                             # [linux]
    - {{ pin_compatible('libglu') }}    # [linux]

test:
  files:
    - test
  requires:
    - {{ compiler('c') }}
    - cmake
    - ninja-base
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libxfixes-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux and not s390x]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
  # test commands are moved to run_test.sh and run_test.bat

about:
  home: https://freeglut.sourceforge.net/
  dev_url: https://github.com/freeglut/freeglut
  doc_url: https://freeglut.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A GUI based on OpenGL.
  description: |
    Open-source alternative to the OpenGL Utility Toolkit (GLUT) library.

extra:
  recipe-maintainers:
    - jakirkham
    - shadowwalkersb
    - wolfv