{% set version = "3.0.0" %}

package:
  name: freeglut
  version: {{ version }}

source:
  fn: freeglut-{{ version }}.tar.bz2
  url: http://sourceforge.net/projects/freeglut/files/freeglut/{{ version }}/freeglut-{{ version }}.tar.gz
  md5: 90c3ca4dd9d51cf32276bc5344ec9754

build:
  number: 0
  skip: true                      # [osx]

requirements:
  build:
    - cmake
    - python  # [win]

test:
  requires:
    python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    # Test includes.
    - test -d "${PREFIX}/include/GL"  # [linux]

      # Test libraries.
    - test -f "${PREFIX}/lib/libglut.a"  # [linux]
    - test -f "${PREFIX}/lib/libglut.so"  # [linux]
    - ldd "${PREFIX}/lib/libglut.so"  # [linux]

about:
  home: http://freeglut.sourceforge.net/
  license: MIT
  summary: A GUI based on OpenGL.

extra:
  recipe-maintainers:
    - jakirkham
