{% set version = "3.2.2" %}

package:
  name: freeglut
  version: {{ version }}

source:
  fn: freeglut-{{ version }}.tar.bz2
  url: http://sourceforge.net/projects/freeglut/files/freeglut/{{ version }}/freeglut-{{ version }}.tar.gz
  sha256: c5944a082df0bba96b5756dddb1f75d0cd72ce27b5395c6c1dde85c2ff297a50
  patches:
    - disable_autolink_windows.patch
    - 96.patch

build:
  number: 0
  skip: true  # [osx]
  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=freeglut
    # very good backwards compatibility
    - {{ pin_subpackage("freeglut", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                               # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libxfixes-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
  host:
    - libglu                             # [linux]
    - libxcb                             # [linux]
  run:
    - libxcb                             # [linux]

test:
  files:
    - test

  requires:
    - {{ compiler('c') }}
    - cmake
    - ninja
    - libglu                             # [linux]
    - libxcb                             # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libxfixes-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]

  commands:
    # Test includes.
    - test -d "${PREFIX}/include/GL"  # [linux]

      # Test libraries.
    - test ! -f "${PREFIX}/lib/libglut.a"   # [linux]
    - test -f "${PREFIX}/lib/libglut.so"    # [linux]
    - ldd "${PREFIX}/lib/libglut.so"        # [linux]

    # Test Windows includes and libraries.
    - if not exist %LIBRARY_INC%\\GL\\freeglut.h     exit 1   # [win]
    - if not exist %LIBRARY_INC%\\GL\\freeglut_ext.h exit 1   # [win]
    - if not exist %LIBRARY_INC%\\GL\\freeglut_std.h exit 1   # [win]
    - if not exist %LIBRARY_INC%\\GL\\glut.h         exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\freeglut.lib       exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\freeglut.dll       exit 1   # [win]

about:
  home: http://freeglut.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A GUI based on OpenGL.

extra:
  recipe-maintainers:
    - jakirkham
    - shadowwalkersb
    - wolfv