# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YsbldV/Kx08dPydVAgaLzuOKg0Gq4j53cU58x6ecGOuJKf6MQS2hRP0fkoMOfdlpYp96rxbhLS5QbXc2MNjdqPaxNOSk/yoySzXGtoA30BcVmMxEoCe8VgLHAcXdS+EHYNrM//l62VzcAqmx7GWnVTGYISbXOhDhkb8YKk94vV1UTPwpfuWkvVHbCFKFCsqgllNblx4gBS/25vOVlZRkV9/hM5DDGW1PuOaYlQHWDpYZogVlk2WYmS0LnjCxOxEePArld8yvpuw3Y6NteoX0iAWQuXL5jkXwN3NrP8alG28Eqm7dnb90I4Tg6Rby8LrYYQq0gzeGtt8o8vHc7MsgNkcpsNjuNg6PLoShxGnOmpwhV7WJEMs9FPc1K2RF4WPrUPIJBKj1U/h4aetn0b2FyjgUBbNufjoaZkZ15Vqiy6yXTdcDQZy4bFH6wIir+hLXcL+2DxtG5GVvRAzgojp+2JXmCdU/Ide7bX5hR0wrZYdy4PdFBo9trE+MXCFpjgn+wIZkCDZByBJ5c/BZgOl8TldEtty365YVwCPKJwXz7ov0gICUJAauI1PYgoAxE98xZJ0IeOAcpIMt4HRYMIpf93tSwVlHfgtz9uZLhG0jVVl+NSsyUGWm8nPUrerQ4KcElFoiE+RE4gRdlfkp/xH9QtHvBgnc+HTlmcBu0qbX/CI="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
