travis:
  secure:
    BINSTAR_TOKEN: D7wZndpldVgZITPcLeMoESa7GynSjNMBsrfjg95o+upuKt0vyOSf1tzJ1xf8yL5p94RsLie9Sh1kHQLS8zP4eZj18cS36HzhHu3QxZSBU/I1fZ3gay1rWMg2/qy+o2zHYDA+xDRF1rk9VWuQLtPr1sb8YsOLktyeDg5uC/aCLBhkwSOtFmWcVeQqa3afRQNR9jMb1wwCRAYODNMcj568YeNatwd3YdB7Kt7HuL6pN4h65H4a0mcGfntHz0qmmB7Qbawc05jMgk724cpM6QHEqXBJkNt5z/FDXFbjXcm8EjuvcQvzn1MmZsak4s38RwkhAiY+G+fECF5zj7Dkbcnnq/m8BKp8Odh9c30/J4fb0YrA9wxHMRK7fcdTTPBWJ7ZAlmbXIHckKT6cHQDHa1iU5OwmdjIIZmrx1LSuzhN5zaFvXyfLkXnK/Hqbkn9kRXS5igM7XbGTzPHcFwJh5zTkLdkfLMfUGefYyh48EMYRer67Hbcp2fWH/TWXHDOt6ud81r7igP1pT3tNED8Nkb1YwT6XBXXC6JsyrSRXR5EhE8Fd/GHCl4xN89zFT2XvNAHnLmWRN1taHBO89Wv9QpqGvfAIF/KenBZVqZTzEzuJGgP3AKxPfDqEos4kvigCkAmpMR4WMu1jyPov0eD7IJSvX59/Y0grceKkxRwwoY8bgAk=
appveyor:
  secure:
    BINSTAR_TOKEN: 4ef5IUakGqqw7GSfuIp93Q4MdAC1VnweE1kFVAOUs6ThPDQWBqNpGaq6ZuEbX1FL
