travis:
  secure:
    BINSTAR_TOKEN: YsbldV/Kx08dPydVAgaLzuOKg0Gq4j53cU58x6ecGOuJKf6MQS2hRP0fkoMOfdlpYp96rxbhLS5QbXc2MNjdqPaxNOSk/yoySzXGtoA30BcVmMxEoCe8VgLHAcXdS+EHYNrM//l62VzcAqmx7GWnVTGYISbXOhDhkb8YKk94vV1UTPwpfuWkvVHbCFKFCsqgllNblx4gBS/25vOVlZRkV9/hM5DDGW1PuOaYlQHWDpYZogVlk2WYmS0LnjCxOxEePArld8yvpuw3Y6NteoX0iAWQuXL5jkXwN3NrP8alG28Eqm7dnb90I4Tg6Rby8LrYYQq0gzeGtt8o8vHc7MsgNkcpsNjuNg6PLoShxGnOmpwhV7WJEMs9FPc1K2RF4WPrUPIJBKj1U/h4aetn0b2FyjgUBbNufjoaZkZ15Vqiy6yXTdcDQZy4bFH6wIir+hLXcL+2DxtG5GVvRAzgojp+2JXmCdU/Ide7bX5hR0wrZYdy4PdFBo9trE+MXCFpjgn+wIZkCDZByBJ5c/BZgOl8TldEtty365YVwCPKJwXz7ov0gICUJAauI1PYgoAxE98xZJ0IeOAcpIMt4HRYMIpf93tSwVlHfgtz9uZLhG0jVVl+NSsyUGWm8nPUrerQ4KcElFoiE+RE4gRdlfkp/xH9QtHvBgnc+HTlmcBu0qbX/CI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
