travis:
  secure:
    BINSTAR_TOKEN: dg/tZrMbBt+dEUDMsXDtyNeonApsKcYnrL2zuj0UPQKCVQdUJtPixR6HIoVut5XaKcRfbv1Lwqb2xQwN9PufIr238Z81nRsFmCc/7ZJ/9ce+H/+dXUdvkgoFOQiWTgQw4HjsVqLZB/NfSbgXY2qw+GJqoQMG53BY8wFEyTJwLOJLO9EItXL/H8n50aYEf2deX/23C9rXM9dKkZiEttCVHgDZHQiEg5JKiXA9LMBnldEKCsUyorOXjTNv5OY21OrWMEjw2fMH6tbY2l3/QnE0hBemafReu92SZSIYtF8byayBFrVAb7OjXKiCRvJM1MTN2HUjCAENQTFAj7Tyi9RN0tb+tA0lVVRnZmWwD3eiSRaKWk14jki81ZSVFX9Zb2UmdzqV0p140YNGMHrmRuaJjqLK+AmbZyFnwA+MVl48mgqXctktvntqtX4EJWhDuAsyJpq4hnOsUClZiWHasvaCWWfzpHI68/XKf4pKOoAhoq2eOtFIfsMFYpwC7PAnt3dPHqWJrJbz6FBG7kaDmkRuntt23w6zSHRzF4Sh91H+j1NFUWW81NP6cZc4PED+euPUmy8ZlUoKNryOml8DRHsEu1VC9oe8KPVijKYjtQB5WqYeul5GA38xyOHxLfH6c0Hsya9b4Cxpufd2kti5pyjD9qFfT1nj2J8nbZkQYayl4+g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
